name: Ejecutar Ticker Manualmente

on:
  workflow_dispatch: # Este es el disparador manual

jobs:
  run-script: # Nombre del trabajo
    runs-on: ubuntu-latest

    steps:
      - name: Descargar código
        uses: actions/checkout@v4 # Actualizado a la versión más reciente (v4)

      - name: Instalar Python y dependencias
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client google-generativeai
          pip install yfinance pandas
          pip install yfinance pandas feedparser # Incluido según tu workflow funcional

      - name: Ejecutar script de análisis de ticker manual
        env:
          # Se mantienen solo las variables de entorno necesarias para Gemini y autenticación
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          # Las variables SPREADSHEET_ID y RANGE_NAME se han eliminado ya que este script no lee de Google Sheets
        run: |
          python analizar_ticker_manual.py # Ejecuta el nuevo script
