name: Ejecutar Premium

on:
  workflow_dispatch: # Este es el disparador manual

jobs:
  run-script: # Nombre del trabajo
    runs-on: ubuntu-latest

    steps:
      - name: Descargar código
        uses: actions/checkout@v4 # Actualizado a la versión más reciente (v4)

      - name: Instalar Python y dependencias
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client google-generativeai
          pip install yfinance pandas
          pip install yfinance pandas feedparser # Incluido según tu workflow funcional

      - name: Ejecutar script de análisis de ticker manual
        env:
          # ¡Ahora se incluyen TODAS las variables de entorno, igual que en tu workflow funcional!
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
          SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }} # Re-incluida
          RANGE_NAME: 'A1:C10' # Re-incluida, ajusta si es necesario en tus secretos
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          python Premium.py # Ejecuta el nuevo script
